#File generated by Pentaho Translator for package 'org.pentaho.di.core.database' in locale 'zh_CN'


#Wed Apr 23 12:53:18 CST 2008
Database.CreatingConnectionPool=\u4E3A''{0}''\u521B\u5EFA\u6570\u636E\u5E93\u8FDE\u63A5\u6C60...
DatabaseMeta.report.ConnectionError=\u9519\u8BEF\u8FDE\u63A5\u6570\u636E\u5E93 [{0}] \: 
DatabaseMeta.report.ConnectionOk=\u6B63\u786E\u8FDE\u63A5\u5230\u6570\u636E\u5E93[{0}] 
DatabaseUtil.DSNotFound=\u65E0\u6548\u7684\u6570\u636E\u6E90\:''{0}''
Database.UnableToPreLoadConnectionToConnectionPool.Exception=\u4E0D\u80FD\u4E3A\u8FDE\u63A5\u6C60\u9884\u52A0\u8F7D\u8FDE\u63A5
DatabaseMeta.report.Hostname=\u4E3B\u673A\u540D       \: 
DatabaseMeta.report.Port=\u7AEF\u53E3           \: 
BaseDatabaseMeta.TestConnectionReportNotImplemented.Message=\u5BF9\u4E0D\u8D77,\u4E0D\u80FD\u4E3A\u8BE5\u6570\u636E\u5E93\u521B\u5EFA\u6D4B\u8BD5\u62A5\u544A.
DatabaseMeta.report.DatabaseName=\u6570\u636E\u5E93\u540D\:
Database.UnableToCheckIfConnectionPoolExists.Exception=\u68C0\u67E5\u8FDE\u63A5\u6C60\u662F\u5426\u88AB\u6CE8\u518C\u65F6\u53D1\u751F\u9519\u8BEF.
DatabaseMeta.report.ConnectionWithPartError=\u9519\u8BEF\u8FDE\u63A5\u5206\u533AID\u4E3A[{1}]\u7684\u6570\u636E\u5E93[{0}]\: {2}
DatabaseMeta.report.ConnectionWithPartOk=\u6B63\u786E\u8FDE\u63A5\u5206\u533AID\u4E3A[{1}]\u7684\u6570\u636E\u5E93[{0}]
Database.CreatedConnectionPool=\u4E3A''{0}''\u521B\u5EFA\u6570\u636E\u5E93\u8FDE\u63A5\u6C60\u6210\u529F
Database.UnableToLoadConnectionPoolDriver.Exception=\u4E0D\u80FD\u4E3A\u8FDE\u63A5\u6C60 [{0}] \u548C\u7C7B [{1}] \u52A0\u8F7D\u9A71\u52A8
