#File generated by Pentaho Translator for package 'org.pentaho.di.trans.steps.addsequence' in locale 'ja_JP'
#
#
#Fri Apr 04 19:39:32 JST 2008
AddSequenceDialog.NoValidConnectionError.DialogMessage=\u30C7\u30FC\u30BF\u30BD\u30FC\u30B9\u304C\u9078\u629E\u3055\u308C\u3066\u3044\u307E\u305B\u3093\u3002
AddSequenceDialog.Log.GettingKeyInfo=\u30AD\u30FC\u3092\u53D6\u5F97\u4E2D\u3067\u3059...
AddSequence.Log.WriteRow=Wrote row \#
AddSequence.Log.ConnectedDB=Connected to database...
AddSequence.Exception.CouldNotFindNextValueForSequence=Couldn''t find next value for sequence \: 
AddSequence.Log.ErrorInStep=Because of an error, this step can''t continue\: 
AddSequenceDialog.TargetSchema.Label=\u30B9\u30AD\u30FC\u30DE\u540D
AddSequenceDialog.UseDatabase.Label=\u30B7\u30FC\u30B1\u30F3\u30B9\u30AB\u30A6\u30F3\u30BF\u3092\u53D6\u5F97\u3059\u308B
AddSequenceMeta.ErrorMessage.UnableToConnectDB=I was unable to connect to the database to verify the status of the table.
AddSequenceDialog.UseCounter.Tooltip=\u5185\u90E8\u30AB\u30A6\u30F3\u30BF\u3092\u4F7F\u7528\u3059\u308B\u5834\u5408\u306F\u30C1\u30A7\u30C3\u30AF\u30DC\u30C3\u30AF\u30B9\u3092\u6709\u52B9\u306B\u3057\u3066\u304F\u3060\u3055\u3044\u3002
AddSequence.Log.CouldNotConnectToDB=Step couldn''t connect to the database\: 
AddSequenceDialog.UseDatabaseGroup.Label=\u30B7\u30FC\u30B1\u30F3\u30B9\u30AB\u30A6\u30F3\u30BF\u306E\u53D6\u5F97
AddSequence.Log.TransformationCountersHashtableNotAllocated=Sorry, Transformation counters hash table not allocated\! (internal error)
AddSequenceDialog.UseDatabase.Tooltip=\u30C7\u30FC\u30BF\u30D9\u30FC\u30B9\u304B\u3089\u30B7\u30FC\u30B1\u30F3\u30B9\u30AB\u30A6\u30F3\u30BF\u3092\u53D6\u5F97\u3059\u308B\u5834\u5408\u306F\u30C1\u30A7\u30C3\u30AF\u30DC\u30C3\u30AF\u30B9\u3092\u6709\u52B9\u306B\u3057\u3066\u304F\u3060\u3055\u3044\u3002
AddSequenceMeta.Exception.UnableToReadStepInfo=Unable to read step information from the repository for id_step\=
AddSequenceMeta.CheckResult.NoInputReceived.Title=No input received from other steps\!
AddSequenceDialog.StartAt.Label=\u958B\u59CB\u5024
AddSequenceDialog.UseCounter.Label=\u5185\u90E8\u30AB\u30A6\u30F3\u30BF\u3092\u4F7F\u7528\u3059\u308B
AddSequence.Log.NeedToSelectSequence=You need to select to create a sequence either using a database or an internal counter.
AddSequenceDialog.Valuename.Label=\u30B7\u30FC\u30B1\u30F3\u30B9\u30AB\u30A6\u30F3\u30BF\u540D
AddSequenceDialog.NoValidConnectionError.DialogTitle=\u30A8\u30E9\u30FC
AddSequence.Exception.NoSpecifiedMethod=No method is specified in this step\!
AddSequence.Log.ReadRow=Read row \#
AddSequenceDialog.UseCounterGroup.Label=\u30B7\u30FC\u30B1\u30F3\u30B9\u30AB\u30A6\u30F3\u30BF\u306E\u751F\u6210
AddSequenceDialog.CounterName.Label=\u30AB\u30A6\u30F3\u30BF\u540D(\u30AA\u30D7\u30B7\u30E7\u30F3)
AddSequenceDialog.IncrBy.Label=\u5897\u5206
AddSequenceMeta.ErrorMessage.NoConnectionDefined=There is no connection defined in this step.
AddSequence.Log.CouldNotParseCounterValue=Counter value for {0} could not be parsed, original value is [{1}] which becomes [{2}]. Error\: {3}. 
AddSequenceDialog.Shell.Title=Get sequence value from database
AddSequence.Exception.ErrorReadingSequence=Error reading next value of sequence [{0}] from database
AddSequenceMeta.CheckResult.SequenceCouldNotBeFound.Title=The sequence [{0}] couldn''t be found
AddSequenceDialog.Seqname.Label=\u30B7\u30FC\u30B1\u30F3\u30B9\u540D
AddSequence.Log.CountersWithDifferentCharacteristics=Counter [{0}] is defined multiple times with different characteristics.
AddSequenceDialog.StepName.Label=\u30B9\u30C6\u30C3\u30D7\u540D
AddSequenceMeta.Exception.ErrorLoadingStepInfo=Error loading step info from XML
AddSequence.Log.LineNumber=linenr 
AddSequenceMeta.Exception.UnableToSaveStepInfo=Unable to save step info to the repository for id_step\=
AddSequenceDialog.MaxVal.Label=\u6700\u5927\u5024
AddSequenceMeta.CheckResult.SequenceExists.Title=Sequence exits.
AddSequenceMeta.CheckResult.StepIsReceving.Title=Step is receiving info from other steps.
AddSequenceMeta.CheckResult.UnableToConnectDB.Title=Unable to connect to database to verify sequence because of an error\: 
